apiVersion: v1
kind: Pod
metadata:
  name: podeventlogger
  namespace: default
spec:
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: p100-1
  serviceAccountName: octopus-tasksetcontroller
  containers:
  - name: podeventlogger
    image: yzs981130/podeventlogger:version-0.0.2
    command: ["PodEventLogger"]
    #args: ["--kubeconfig","/log/config"]
    imagePullPolicy: Always
    volumeMounts:  
    - name: logdir
      mountPath: /log 
  volumes: 
  - name: logdir  
    hostPath:  
      path: /home/amax/yezhisheng/log
